###############
### WINDOWS ###
###############

# https://wiki.hypr.land/Configuring/Window-Rules/
windowrule {
        name = blueman
        match:class = .*blueman.*
        workspace = 1
}

windowrule {
        name = audio
        match:class = .*(QjackCtl|gpwgraph).*
        workspace = 1
}

windowrule {
        name = browser
        match:class = ^($BROWSER)$
        workspace = 2
}

windowrule {
        name = mpv
        match:class = ^(mpv)$
        workspace = 3
        fullscreen = on
        # no_initial_focus = on
        opaque = on
}

windowrule {
        name = steam
        match:class = ^(steam)$
        workspace = 4
        no_initial_focus = on
}

windowrule {
        name = term-menu
        match:class = ^(term-menu)$
        workspace = special
        float = on
        size = 1000 500
}

windowrule {
        name = keepassxc
        match:class = .*KeePassXC.*
        workspace = special:scratchpad
}

##################
### WORKSPACES ###
##################

# https://wiki.hypr.land/Configuring/Workspace-Rules/
workspace = 1, on-created-empty:$TERMINAL -e tmux new-session -A -s init
workspace = 2, on-created-empty:$BROWSER
workspace = 3, on-created-empty:$TERMINAL -e tmux new-session -A -s media
