# let's CLIs change window title
[window]
dynamic_title = true

[font]
normal = { family = "HasklugNerdFontMono" }
size = 11

# colour palette (gruvbox material)
[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

## colour palette (Gruvbox dark)
## Default colors
#[colors.primary]
## hard contrast background = = '#1d2021'
#background = '#282828'
## soft contrast background = = '#32302f'
#foreground = '#ebdbb2'
#
## Normal colors
#[colors.normal]
#black   = '#282828'
#red     = '#cc241d'
#green   = '#98971a'
#yellow  = '#d79921'
#blue    = '#458588'
#magenta = '#b16286'
#cyan    = '#689d6a'
#white   = '#a89984'
#
## Bright colors
#[colors.bright]
#black   = '#928374'
#red     = '#fb4934'
#green   = '#b8bb26'
#yellow  = '#fabd2f'
#blue    = '#83a598'
#magenta = '#d3869b'
#cyan    = '#8ec07c'
#white   = '#ebdbb2'
