#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & #load sxhkd
picom & #load picom
killall -q polybar; polybar & #kill and set new polybar instance
feh --bg-scale "$HOME/.dotfiles/wallpaper.jpg" & #set wallpaper
xrandr -r 120 & #set monitor refresh rate

# Autostart script
startup_lock=/tmp/autostart.lock
if [ ! -e $startup_lock ]; then
	$HOME/.bin/autostart
        touch $startup_lock &
fi

# define workspaces
bspc monitor -d  󰈹     VII VIII 󱡬 󰭹

# define default appearance
bspc config normal_border_color "#282A2E"
bspc config focused_border_color "#e3a84a"
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config top_padding         12
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer follows focus

# spawn specified app only in specified workspace 
bspc rule -a Blueman-manager desktop='^1' 
bspc rule -a firefox --one-shot desktop='^2' 
bspc rule -a mpv desktop='^3'
bspc rule -a rss desktop='^3'
bspc rule -a steam desktop='^4'
bspc rule -a KeePassXC desktop='^5'
bspc rule -a QjackCtl desktop='^9'
bspc rule -a discord desktop='^10'
